### ISSUE TITLE
生产环境在后台启用验证码后报错

### ISSUE THREAD

**Issue by yangrongzhou** [guanguans/dcat-login-captcha#27]
**Describe the bug**
在生产环境后台扩展管理中，启用验证码，之后页面就报“500|服务器错误”了，导致无法正常显示。

**To Reproduce**
1.生产环境安装了验证码扩展包，暂未启用
2.生产环境开启了配置缓存
3.登录Dcat后台，在 "系统-扩展" 菜单中将验证码扩展升级至“版本 1.0.19”
4.点击验证码扩展的“启用”按钮
5.然后页面就报“500|服务器错误”，后台所有页面都无法使用了

**Screenshots**
查看 laravel.log 日志，报错内容如下：
```
[2023-02-25 14:52:05] production.ERROR: Unsupported operand types: array + null {"exception":"[object] (TypeError(code: 0): Unsupported operand types: array + null at /www/wwwroot/xxx.com/vendor/guanguans/dcat-login-captcha/src/LoginCaptchaServiceProvider.php:92)
[stacktrace]
#0 /www/wwwroot/xxx.com/vendor/guanguans/dcat-login-captcha/src/LoginCaptchaServiceProvider.php(35): Guanguans\\DcatLoginCaptcha\\LoginCaptchaServiceProvider->setupConfig()
#1 /www/wwwroot/xxx.com/vendor/dcat/laravel-admin/src/Extend/ServiceProvider.php(92): Guanguans\\DcatLoginCaptcha\\LoginCaptchaServiceProvider->init()
...
```

第92行代码为：
```
static::setting((array) static::setting() + config('login_captcha'));
```
也就是说`config('login_captcha')`的结果是null。

**Additional context**
我的php版本为8.1.9，composer依赖包如下：
```
    "require": {
        "php": "^8.1",
        "ext-bcmath": "*",
        "dcat/laravel-admin": "2.*",
        "guanguans/dcat-login-captcha": "^1.0",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "overtrue/laravel-wechat": "^7.2",
        "w7corp/easywechat": "^6.7"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel-lang/common": "^3.1",
        "laravel/envoy": "^2.8",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },
```

在生成环境安装composer包，然后缓存配置：
```
php composer install -o --no-dev
php artisan config:cache
php artisan route:cache
php artisan view:cache
```

打开生成的配置缓存文件`bootstrap/cache/config.php`，发现并无`login_captcha`节点。

目前解决办法是：
手动复制`vendor/guanguans/dcat-login-captcha/config/login_captcha.php`一份到`config/login_captcha.php`，再重新执行
```
php composer install -o --no-dev
php artisan config:cache
php artisan route:cache
php artisan view:cache
```
但文档并没有说明需要手动复制这个配置文件！

**Comment by guanguans** [comment]
尝试更新到最新版本。
